title: Kaja Dobrovoljc
logo: "/images/logo.png?raw=true" 
description: >
  View me on:
  Google Scholar
  ResearchGate
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a>
  <br><br>
  Address:
  line1
  line2
  <br><br>
  Contact me:
  kaja.dobrovoljc at ijs.si
  kaja.dobrovoljc at ff.uni-lj.si
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
