title: Kaja Dobrovoljc
logo: "/images/logo.png?raw=true" 
description: >

I am a linguist/researcher interested in design, creation and evaluation of digital language resources and their use in corpus linguistic research.
<br><br>
I currently split my time between [Department of Translation](https://prevajalstvo.ff.uni-lj.si/en) at the Faculty of Arts, University of Ljubljana, [Laboratory for Cognitive Modelling](https://www.fri.uni-lj.si/en/laboratory/lkm) at the Faculty of Computer and Information Science, UL, and [Department for Artificial Intelligence](https://ailab.ijs.si/) at the Jožef Stefan Institute. 
<br><br>
[View my Google Scholar profile](https://scholar.google.com/citations?user=KWq-H4AAAAAJ&hl=en)
[View my ResearchGate profile](https://www.researchgate.net/profile/Kaja-Dobrovoljc)
<br><br>

Contact me:
kaja.dobrovoljc at ijs.si
kaja.dobrovoljc at ff.uni-lj.si
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
