logo: "/images/r17.png?raw=true"
title: Kaja Dobrovoljc
description: >
 Linguist interested in digital language resources, corpus linguistics and natural language processing.
 <br><br>
 Contact:
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ijs.si</a>
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ff.uni-lj.si</a>
   
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


