title: Kaja Dobrovoljc
logo: "/images/logo.png?raw=true"
description: >
  I am a linguist/researcher interested in design, creation and evaluation of digital language resources and their use in corpus linguistic research.
  <br><br>
  I currently split my time between <a href="https://prevajalstvo.ff.uni-lj.si/en">Department of Translation</a> at the Faculty of Arts, University of Ljubljana, <a href="https://www.fri.uni-lj.si/en/laboratory/lkm">Laboratory for Cognitive Modelling</a> at the Faculty of Computer and Information Science, UL, and <a href="https://ailab.ijs.si/">Department for Artificial Intelligence</a> at the Jožef Stefan Institute. 
  <br><br>
  <a href="https://scholar.google.com/citations?user=KWq-H4AAAAAJ&hl=en">View My Google Scholar Profile</a>
  <br><br>
  "Contact me:"
  kaja.dobrovoljc at ijs.si
  kaja.dobrovoljc at ff.uni-lj.si
   
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


