logo: "/images/r17.jpg?raw=true"
title: Kaja Dobrovoljc
description: >
 Linguist interested in digital language resources, corpus linguistics and language technology.
 <br><br>
 Contact:
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ijs.si</a>
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ff.uni-lj.si</a>
   
   
theme: jekyll-theme-minimal
google_analytics: UA-209760355-1


