logo: "/images/r17.jpg?raw=true"
title: Kaja Dobrovoljc
description: >
 Linguist interested in digital language resources, corpus linguistics and language technology.
 <br><br>
 Contact:
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ijs.si</a>
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ff.uni-lj.si</a>
  <br><br>
  How to pronounce:
   <br>
  <a href="http://ipa-reader.xyz/?text=ka%3Aja%20d%C9%94br%C9%94%CB%88vo%CB%90lts&voice=Jan" target="_blank">/ka:ja dɔbrɔˈvoːlts/</a>
   
   
theme: jekyll-theme-minimal
google_analytics: UA-209760355-1


