# title: Kaja Dobrovoljc
logo: "/images/logo.png?raw=true"
description: >
 Linguist interested in digital language resources, corpus linguistics and natural language processing.
 <br><br>
  <a href="https://scholar.google.com/citations?user=KWq-H4AAAAAJ&hl=en">View My Google Scholar Profile</a>
  <br><br>
  "Contact me:"
  kaja.dobrovoljc at ijs.si
  kaja.dobrovoljc at ff.uni-lj.si
   
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


