logo: "/images/r197.png?raw=true"
title: Kaja Dobrovoljc
description: >
 Linguist interested in digital language resources, corpus linguistics and natural language processing.
 <br><br>
 Research profiles:
 <br>
  <a href="https://scholar.google.com/citations?user=KWq-H4AAAAAJ&hl=en">Google Scholar</a>
 <br>
  <a href="https://www.researchgate.net/profile/Kaja-Dobrovoljc">ResearchGate</a>
 <br><br>
 Contact:
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ijs.si</a>
 <br>
  <a href="mailto:kaja.dobrovoljc@ijs.si">kaja.dobrovoljc@ff.uni-lj.si</a>
   
   
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here


